### ISSUE TITLE
appimagetool says Desktop file not found, aborting

### ISSUE THREAD

**Issue by ilmari-lauhakangas** [antoniofaccioli/libreoffice-appimage#28]
Ran script with
`./make_libreoffice_appimage fresh x86-64 N N N N Y`

Fresh was 7.1.1 at the time.

Failure:

```
Saving to: 'appimagetool'

appimagetool                 100%[==============================================>]   2.07M  9.32MB/s    in 0.2s    

2021-03-27 09:51:56 (9.32 MB/s) - 'appimagetool' saved [2172096/2172096]

+ chmod a+x ./appimagetool
+ set +x
appimagetool, continuous build (commit 8bbf694), build <local dev build> built on 2020-12-31 11:48:33 UTC
Desktop file not found, aborting
+ [[ N == \Y ]]
+ mkdir -p ../out/
+ mv '*.AppImage*' ../out/
mv: cannot stat '*.AppImage*': No such file or directory
```

**Comment by antoniofaccioli** [comment]
You can try again? I just tried building the daily packages again and it works.
And I had already created 7.1.1 packages (portable or no portable):
https://libreoffice.soluzioniopen.com/stable-2/
https://libreoffice.soluzioniopen.com/index.php/stable-fresh-portable/
https://libreoffice.soluzioniopen.com/stable-fresh-not-portable/

My system is an ubuntu 18.04

**Comment by ilmari-lauhakangas** [comment]
Still failing on Arch Linux

**Comment by ederag** [comment]
Same issue on `openSUSE Leap 15.2`, with `./make_libreoffice_appimage daily x86-64 N N N N Y`
Actually, the `find ../ -name '*.deb' -exec dpkg -x '{}' . ';'` line failed with 
`find: ‘dpkg’: No such file or directory` because `dpkg` was missing.
After installation (`sudo zypper install dpkg`), it works fine.
Thanks, very handy for testing fixes !

**Comment by ilmari-lauhakangas** [comment]
Argh, sorry for the noise - I missed dpkg
